;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-newline-and-maybe-indent
        js2r-kill
        kill-region-or-backward-word
        open-line-and-indent
        paredit-backward-kill-word
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        paredit-kill-region-or-backward-word
        paredit-semicolon
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        save-region-or-current-line
        yaml-electric-backspace
        ))
